### ISSUE TITLE
Itanium emulator

### ISSUE THREAD

**Issue by DotNetTester** [itanium64/Rosalia64#12]
It would be awesome to create an Itanium emulator that can run the Itanium versions of Windows Server 2003 and Windows Server 2008 R2. You currently need a physical Itanium system to run the Itanium versions of Windows. The Itanium versions of Windows and the Itanium platform are rather obscure. That makes it interesting from a historical and hobbyist perspective.

**Comment by Eeveelution** [comment]
Sorry to burst your bubble but that wouldn't be what this is either way. This was created to run .exe files compiled for Windows on Itanium, not to be a system emulator. That goal was set because Visual Studio 2010 was the only itanium compiler I could get working. And in case you didn't notice, it not being updated in a year means I've abandoned the project. I don't know how MMUs work and don't know enough about the deeper hardware beyond the processor and how that is emulated.
